apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:13.2
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: doo
            - name: POSTGRES_USER
              value: doo
            - name: POSTGRES_PASSWORD
              value: doo
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
  - port: 5432
  selector:
    app: db

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  labels:
    app: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
