name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOO_DB_HOST: localhost
  DOO_DB_PORT: 5432
  DOO_DB_USER: doo
  DOO_DB_PASSWORD: doo
  DOO_DB_NAME: doo

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ env.DOO_DB_NAME }}
          POSTGRES_USER: ${{ env.DOO_DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DOO_DB_PASSWORD }}
        ports:
          - 5432:5432

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: prepare go env
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: run tests
        run: make coverage

      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          files: coverage.txt
          fail_ci_if_error: true
